#!/bin/sh

# Config
DEVICE=/dev/cd0
LOGDIR=/mnt/freerip/logs

# arg parsing
CDEV="$1"

# execute
identify $CDEV

LOGFILE=$LOGDIR/$TITLE.log

rip-video "/mnt/TV Shows/$TITLE.mkv" | tee $LOGFILE
eject $DEVICE
